### import

In [2]:
from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams, Distance,PayloadSchemaType,PointStruct,MatchAny,FieldCondition,Filter,Prefetch, FusionQuery

import pandas as pd
import numpy as np
import openai
import json
import tiktoken

c:\Users\Loq\Documents\CRAP\end to end aibootcamp\code\handsON\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

#### Retrive all item ids from amazon items qdrant collections

In [3]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [4]:
dummy_vector = np.zeros(1536).tolist()

In [5]:
payload=qdrant_client.query_points(
        collection_name="amazon-items-collection-02-openai-small",
        
        query=dummy_vector,
        using="text-embedding-3-small",
        limit=1000,
        with_payload=["parent_asin"],
        with_vectors=False,
)

In [6]:
payload.points

[ScoredPoint(id=63, version=1, score=0.0, payload={'parent_asin': 'B09V2TBVHV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=28, version=1, score=0.0, payload={'parent_asin': 'B0BJFPFR2Z'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=44, version=1, score=0.0, payload={'parent_asin': 'B0B4KFSLVW'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=4, version=1, score=0.0, payload={'parent_asin': 'B0BS1SHT91'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=29, version=1, score=0.0, payload={'parent_asin': 'B09R84DXR1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=13, version=1, score=0.0, payload={'parent_asin': 'B0B5B8JP2T'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=53, version=1, score=0.0, payload={'parent_asin': 'B004GPEB50'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=2, version=1, score=0.0, payload={'parent_asin': 'B09Q98326Z'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=42, version=1, score=0.0, payload={'parent_asin': 'B09TGDWJRP'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=52, version=1, score=0.0, payload={'parent_asin': 'B0BPN1K83D'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=55, version=1, score=0.0, payload={'parent_asin': 'B0B14G1W9T'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=26, version=1, score=0.0, payload={'parent_asin': 'B09R1C2F83'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=9, version=1, score=0.0, payload={'parent_asin': 'B00A2K7LG4'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=27, version=1, score=0.0, payload={'parent_asin': 'B09RQGFDDW'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=34, version=1, score=0.0, payload={'parent_asin': 'B0BL4VY2NB'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=15, version=1, score=0.0, payload={'parent_asin': 'B0BTW59YJJ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=49, version=1, score=0.0, payload={'parent_asin': 'B0BS48V39J'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=35, version=1, score=0.0, payload={'parent_asin': 'B0B1QVBDSK'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=54, version=1, score=0.0, payload={'parent_asin': 'B09SP9JXV9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=17, version=1, score=0.0, payload={'parent_asin': 'B09YTJPYM4'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=33, version=1, score=0.0, payload={'parent_asin': 'B0BJ35953K'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=58, version=1, score=0.0, payload={'parent_asin': 'B0B91C6BSR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=21, version=1, score=0.0, payload={'parent_asin': 'B09NBJJGGX'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=36, version=1, score=0.0, payload={'parent_asin': 'B09VGGZKFN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=32, version=1, score=0.0, payload={'parent_asin': 'B0BJVZQB6S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=51, version=1, score=0.0, payload={'parent_asin': 'B0BJ1CVBQY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=59, version=1, score=0.0, payload={'parent_asin': 'B0B2HTZ54Z'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=8, version=1, score=0.0, payload={'parent_asin': 'B0BN8LTKRD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=39, version=1, score=0.0, payload={'parent_asin': 'B0BSNRV2Z3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=30, version=1, score=0.0, payload={'parent_asin': 'B09PP8QPTZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=281, version=5, score=0.0, payload={'parent_asin': 'B0BG3F848Q'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=264, version=5, score=0.0, payload={'parent_asin': 'B09SXRT2LR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=278, version=5, score=0.0, payload={'parent_asin': 'B09TFVBKNH'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=294, version=5, score=0.0, payload={'parent_asin': 'B09S9WTGX7'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=272, version=5, score=0.0, payload={'parent_asin': 'B0B225YLCD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=286, version=5, score=0.0, payload={'parent_asin': 'B0B4P55X7P'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=297, version=5, score=0.0, payload={'parent_asin': 'B0B2X5W3YH'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=268, version=5, score=0.0, payload={'parent_asin': 'B09TN23LF5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=260, version=5, score=0.0, payload={'parent_asin': 'B0B6GGYWMS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=318, version=5, score=0.0, payload={'parent_asin': 'B0BWFRVVT2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=284, version=5, score=0.0, payload={'parent_asin': 'B0BHFKN43K'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=289, version=5, score=0.0, payload={'parent_asin': 'B09S5JJDFQ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=310, version=5, score=0.0, payload={'parent_asin': 'B0B8DWKX13'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=288, version=5, score=0.0, payload={'parent_asin': 'B09ZKJJ62H'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=257, version=5, score=0.0, payload={'parent_asin': 'B0BFP93P9T'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=266, version=5, score=0.0, payload={'parent_asin': 'B09Q12DWG2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=319, version=5, score=0.0, payload={'parent_asin': 'B0BD4XPYYM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=279, version=5, score=0.0, payload={'parent_asin': 'B0B94TZTZ6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=309, version=5, score=0.0, payload={'parent_asin': 'B09X257ZY5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=265, version=5, score=0.0, payload={'parent_asin': 'B0B6J6632J'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=304, version=5, score=0.0, payload={'parent_asin': 'B0B18X4SKS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=313, version=5, score=0.0, payload={'parent_asin': 'B0B4L1SZRY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=298, version=5, score=0.0, payload={'parent_asin': 'B0B1DW3VP6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=274, version=5, score=0.0, payload={'parent_asin': 'B09Q962VN1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=311, version=5, score=0.0, payload={'parent_asin': 'B0BLJM97W1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=312, version=5, score=0.0, payload={'parent_asin': 'B0BFJXBYV1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=320, version=5, score=0.0, payload={'parent_asin': 'B0BPMN3P74'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=291, version=5, score=0.0, payload={'parent_asin': 'B0BD5X3S6J'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=263, version=5, score=0.0, payload={'parent_asin': 'B0BDGB3YRJ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=277, version=5, score=0.0, payload={'parent_asin': 'B0B3QX9JMM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=262, version=5, score=0.0, payload={'parent_asin': 'B0B3JS5743'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=299, version=5, score=0.0, payload={'parent_asin': 'B077P4L1M4'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=571, version=9, score=0.0, payload={'parent_asin': 'B0B8CKYDTS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=576, version=9, score=0.0, payload={'parent_asin': 'B0BS1VVXT1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=573, version=9, score=0.0, payload={'parent_asin': 'B09VYP9LRG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=523, version=9, score=0.0, payload={'parent_asin': 'B09ZN6YVV8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=533, version=9, score=0.0, payload={'parent_asin': 'B0BG9HWGBH'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=528, version=9, score=0.0, payload={'parent_asin': 'B09QQRDZQ8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=534, version=9, score=0.0, payload={'parent_asin': 'B09PNQZHH2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=518, version=9, score=0.0, payload={'parent_asin': 'B09YKSC1JH'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=514, version=9, score=0.0, payload={'parent_asin': 'B09TPT5BHK'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=525, version=9, score=0.0, payload={'parent_asin': 'B01N7VL812'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=539, version=9, score=0.0, payload={'parent_asin': 'B0B3KGH8R7'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=550, version=9, score=0.0, payload={'parent_asin': 'B0BG5QZY1K'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=517, version=9, score=0.0, payload={'parent_asin': 'B09TDT5BF5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=556, version=9, score=0.0, payload={'parent_asin': 'B09TWN296W'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=530, version=9, score=0.0, payload={'parent_asin': 'B09RQC1CK5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=527, version=9, score=0.0, payload={'parent_asin': 'B09R7VJ23H'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=551, version=9, score=0.0, payload={'parent_asin': 'B0BFLT4TJT'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=520, version=9, score=0.0, payload={'parent_asin': 'B0B52NRT2N'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=519, version=9, score=0.0, payload={'parent_asin': 'B0B6XL4HH2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=526, version=9, score=0.0, payload={'parent_asin': 'B0BNJZ1DQW'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=557, version=9, score=0.0, payload={'parent_asin': 'B09X5ZXQ96'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=567, version=9, score=0.0, payload={'parent_asin': 'B0BGLX9W1M'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=564, version=9, score=0.0, payload={'parent_asin': 'B09ZBLTG4Z'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=570, version=9, score=0.0, payload={'parent_asin': 'B09RQ29GJZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=540, version=9, score=0.0, payload={'parent_asin': 'B0BG2ZDW9P'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=574, version=9, score=0.0, payload={'parent_asin': 'B09TVLJ7TY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=563, version=9, score=0.0, payload={'parent_asin': 'B000ECX0K6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=549, version=9, score=0.0, payload={'parent_asin': 'B0B2NWFJ81'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=536, version=9, score=0.0, payload={'parent_asin': 'B0B3233KQV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=569, version=9, score=0.0, payload={'parent_asin': 'B0BN732PK8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=562, version=9, score=0.0, payload={'parent_asin': 'B0BNT5HG6T'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=537, version=9, score=0.0, payload={'parent_asin': 'B0B7SMJ3M7'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=783, version=13, score=0.0, payload={'parent_asin': 'B0B5H5167S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=792, version=13, score=0.0, payload={'parent_asin': 'B09RQFMZ2S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=777, version=13, score=0.0, payload={'parent_asin': 'B0B3GBJKY8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=775, version=13, score=0.0, payload={'parent_asin': 'B09YKNVN8M'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=782, version=13, score=0.0, payload={'parent_asin': 'B09ZCSTHJR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=804, version=13, score=0.0, payload={'parent_asin': 'B09XFH5M32'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=826, version=13, score=0.0, payload={'parent_asin': 'B09QH3C2RL'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=787, version=13, score=0.0, payload={'parent_asin': 'B0BFXPCLWW'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=786, version=13, score=0.0, payload={'parent_asin': 'B0B29KD73G'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=818, version=13, score=0.0, payload={'parent_asin': 'B09PK4R2VB'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=819, version=13, score=0.0, payload={'parent_asin': 'B09R8ZXM1W'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=811, version=13, score=0.0, payload={'parent_asin': 'B09RG5M91Y'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=825, version=13, score=0.0, payload={'parent_asin': 'B0B65S25PG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=790, version=13, score=0.0, payload={'parent_asin': 'B0B3H2WKY3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=821, version=13, score=0.0, payload={'parent_asin': 'B09PVHR52Q'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=802, version=13, score=0.0, payload={'parent_asin': 'B09V3868MP'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=815, version=13, score=0.0, payload={'parent_asin': 'B0BRTGMB4S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=796, version=13, score=0.0, payload={'parent_asin': 'B0C78K5BCK'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=780, version=13, score=0.0, payload={'parent_asin': 'B09ZLKRKL7'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=812, version=13, score=0.0, payload={'parent_asin': 'B09Y96C5S1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=773, version=13, score=0.0, payload={'parent_asin': 'B0BJ5VG1ZM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=788, version=13, score=0.0, payload={'parent_asin': 'B095JN5CMR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=770, version=13, score=0.0, payload={'parent_asin': 'B09VZH5B2R'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=793, version=13, score=0.0, payload={'parent_asin': 'B0BC265MG1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=820, version=13, score=0.0, payload={'parent_asin': 'B09WVQ2K7S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=823, version=13, score=0.0, payload={'parent_asin': 'B09RXSXQ1D'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=797, version=13, score=0.0, payload={'parent_asin': 'B0B6KJL5XJ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=807, version=13, score=0.0, payload={'parent_asin': 'B001BWQA5A'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=805, version=13, score=0.0, payload={'parent_asin': 'B0BMSQN6P2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=827, version=13, score=0.0, payload={'parent_asin': 'B09WQ59DXZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=828, version=13, score=0.0, payload={'parent_asin': 'B09RTYHNT3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=810, version=13, score=0.0, payload={'parent_asin': 'B0B5FSCMQM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=38, version=1, score=0.0, payload={'parent_asin': 'B00BG475CK'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=84, version=2, score=0.0, payload={'parent_asin': 'B09X3NHJPS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=78, version=2, score=0.0, payload={'parent_asin': 'B0BMTDH5XJ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=111, version=2, score=0.0, payload={'parent_asin': 'B09WDZXGQB'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=82, version=2, score=0.0, payload={'parent_asin': 'B0BNW2ZB4D'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=95, version=2, score=0.0, payload={'parent_asin': 'B0B9S127R7'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=69, version=2, score=0.0, payload={'parent_asin': 'B00VKZVPOY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=68, version=2, score=0.0, payload={'parent_asin': 'B09SDBRWM5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=124, version=2, score=0.0, payload={'parent_asin': 'B0B7QJM6PH'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=66, version=2, score=0.0, payload={'parent_asin': 'B09T1ZQHFV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=113, version=2, score=0.0, payload={'parent_asin': 'B0B3DP7YML'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=70, version=2, score=0.0, payload={'parent_asin': 'B0B92FZQK1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=75, version=2, score=0.0, payload={'parent_asin': 'B0B2ZX6H5Q'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=90, version=2, score=0.0, payload={'parent_asin': 'B09SX1YFV7'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=125, version=2, score=0.0, payload={'parent_asin': 'B0B9QRKMZL'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=109, version=2, score=0.0, payload={'parent_asin': 'B0BSJC3JRN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=93, version=2, score=0.0, payload={'parent_asin': 'B0BP3W1JPB'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=112, version=2, score=0.0, payload={'parent_asin': 'B09RTDRXT1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=116, version=2, score=0.0, payload={'parent_asin': 'B09SVZ3XP7'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=128, version=2, score=0.0, payload={'parent_asin': 'B0BLVYCNXK'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=92, version=2, score=0.0, payload={'parent_asin': 'B0BHJ7GVM3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=88, version=2, score=0.0, payload={'parent_asin': 'B09Z82KFR1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=117, version=2, score=0.0, payload={'parent_asin': 'B09KZRWTXS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=72, version=2, score=0.0, payload={'parent_asin': 'B0BKTG4XJF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=126, version=2, score=0.0, payload={'parent_asin': 'B0BLN8HZK3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=91, version=2, score=0.0, payload={'parent_asin': 'B095WFW3HN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=115, version=2, score=0.0, payload={'parent_asin': 'B0B5P5ZJR9'}, vector=None, shard_key=None, order_value=None),

In [7]:
len(payload.points)

1000

In [8]:
parent_asin_list = [point.payload["parent_asin"] for point in payload.points]

In [9]:
parent_asin_list

['B09V2TBVHV',
 'B0BJFPFR2Z',
 'B0B4KFSLVW',
 'B0BS1SHT91',
 'B09R84DXR1',
 'B0B5B8JP2T',
 'B004GPEB50',
 'B09Q98326Z',
 'B09TGDWJRP',
 'B0BPN1K83D',
 'B0B14G1W9T',
 'B09R1C2F83',
 'B00A2K7LG4',
 'B09RQGFDDW',
 'B0BL4VY2NB',
 'B0BTW59YJJ',
 'B0BS48V39J',
 'B0B1QVBDSK',
 'B09SP9JXV9',
 'B09YTJPYM4',
 'B0BJ35953K',
 'B0B91C6BSR',
 'B09NBJJGGX',
 'B09VGGZKFN',
 'B0BJVZQB6S',
 'B0BJ1CVBQY',
 'B0B2HTZ54Z',
 'B0BN8LTKRD',
 'B0BSNRV2Z3',
 'B09PP8QPTZ',
 'B0BG3F848Q',
 'B09SXRT2LR',
 'B09TFVBKNH',
 'B09S9WTGX7',
 'B0B225YLCD',
 'B0B4P55X7P',
 'B0B2X5W3YH',
 'B09TN23LF5',
 'B0B6GGYWMS',
 'B0BWFRVVT2',
 'B0BHFKN43K',
 'B09S5JJDFQ',
 'B0B8DWKX13',
 'B09ZKJJ62H',
 'B0BFP93P9T',
 'B09Q12DWG2',
 'B0BD4XPYYM',
 'B0B94TZTZ6',
 'B09X257ZY5',
 'B0B6J6632J',
 'B0B18X4SKS',
 'B0B4L1SZRY',
 'B0B1DW3VP6',
 'B09Q962VN1',
 'B0BLJM97W1',
 'B0BFJXBYV1',
 'B0BPMN3P74',
 'B0BD5X3S6J',
 'B0BDGB3YRJ',
 'B0B3QX9JMM',
 'B0B3JS5743',
 'B077P4L1M4',
 'B0B8CKYDTS',
 'B0BS1VVXT1',
 'B09VYP9LRG',
 'B09ZN6YVV8',
 'B0BG9HWGBH',
 'B09QQRDZQ8',
 'B09PNQZHH2',
 'B09YKSC1JH',
 'B09TPT5BHK',
 'B01N7VL812',
 'B0B3KGH8R7',
 'B0BG5QZY1K',
 'B09TDT5BF5',
 'B09TWN296W',
 'B09RQC1CK5',
 'B09R7VJ23H',
 'B0BFLT4TJT',
 'B0B52NRT2N',
 'B0B6XL4HH2',
 'B0BNJZ1DQW',
 'B09X5ZXQ96',
 'B0BGLX9W1M',
 'B09ZBLTG4Z',
 'B09RQ29GJZ',
 'B0BG2ZDW9P',
 'B09TVLJ7TY',
 'B000ECX0K6',
 'B0B2NWFJ81',
 'B0B3233KQV',
 'B0BN732PK8',
 'B0BNT5HG6T',
 'B0B7SMJ3M7',
 'B0B5H5167S',
 'B09RQFMZ2S',
 'B0B3GBJKY8',
 'B09YKNVN8M',
 'B09ZCSTHJR',
 'B09XFH5M32',
 'B09QH3C2RL',
 'B0BFXPCLWW',
 'B0B29KD73G',
 'B09PK4R2VB',
 'B09R8ZXM1W',
 'B09RG5M91Y',
 'B0B65S25PG',
 'B0B3H2WKY3',
 'B09PVHR52Q',
 'B09V3868MP',
 'B0BRTGMB4S',
 'B0C78K5BCK',
 'B09ZLKRKL7',
 'B09Y96C5S1',
 'B0BJ5VG1ZM',
 'B095JN5CMR',
 'B09VZH5B2R',
 'B0BC265MG1',
 'B09WVQ2K7S',
 'B09RXSXQ1D',
 'B0B6KJL5XJ',
 'B001BWQA5A',
 'B0BMSQN6P2',
 'B09WQ59DXZ',
 'B09RTYHNT3',
 'B0B5FSCMQM',
 'B00BG475CK',
 'B09X3NHJPS',
 'B0BMTDH5XJ',
 'B09WDZXGQB',
 'B0BNW2ZB4D',
 'B0B9S127R7',
 'B00VKZVPOY',
 'B09SDBRWM5',
 'B0B7QJM6PH',
 'B09T1ZQHFV',
 'B0B3DP7YML',
 'B0B92FZQK1',
 'B0B2ZX6H5Q',
 'B09SX1YFV7',
 'B0B9QRKMZL',
 'B0BSJC3JRN',
 'B0BP3W1JPB',
 'B09RTDRXT1',
 'B09SVZ3XP7',
 'B0BLVYCNXK',
 'B0BHJ7GVM3',
 'B09Z82KFR1',
 'B09KZRWTXS',
 'B0BKTG4XJF',
 'B0BLN8HZK3',
 'B095WFW3HN',
 'B0B5P5ZJR9',
 'B09R912345',
 'B09XX8WXVN',
 'B0BW2LXV4Y',
 'B0B3GFFTL4',
 'B09ZNT36D8',
 'B09W9QXV52',
 'B0B2WMXB6C',
 'B0BGPZN9J4',
 'B0BS9Y71BP',
 'B09RQ4B5ZD',
 'B09T775QCP',
 'B0BYF2FDCC',
 'B09F1FJCH6',
 'B0BBZBRNKV',
 'B09YMP65S4',
 'B0B4PRR4D4',
 'B09XC6N858',
 'B0BQK7SYDJ',
 'B0B2KN5L1Z',
 'B09RPSZ7GG',
 'B0B7SFXB42',
 'B0B92L86VH',
 'B0BP21DWJG',
 'B09TV65GD2',
 'B0BXG6N2Q2',
 'B0BGSW53JC',
 'B09YYXPDZ4',
 'B09RQFGSZL',
 'B09W9SVX44',
 'B0BLJM6HLQ',
 'B0BHKQRPJW',
 'B0BCL2PZGF',
 'B0B1B87HVW',
 'B09RY4S997',
 'B0B3DJC9BQ',
 'B09PP985CF',
 'B0BGCFBTHL',
 'B0B1J83JF2',
 'B09QY26Q9P',
 'B00GS092V4',
 'B0BJKVLHPL',
 'B0B31NN76X',
 'B09P2NLQPF',
 'B09T2S6WW5',
 'B09TWTDGVZ',
 'B0BCG4HS7R',
 'B0BBRPV4TT',
 'B0B84DFHKH',
 'B0BLHVYBRF',
 'B009A9BGBE',
 'B0BSJG2JX8',
 'B00000JWP7',
 'B0B7W843W2',
 'B0B6YDH5V8',
 'B0B6Q6GBFY',
 'B09Q9878SH',
 'B09Z24RYZ1',
 'B09Z6TY5F1',
 'B09P4FTC3B',
 'B0BW4B2NPW',
 'B0B6VC2CPQ',
 'B09T82XX5L',
 'B09TN3BKR6',
 'B0BL212NP3',
 'B09SBQQYWZ',
 'B0BFFL1BR6',
 'B09XFFG62B',
 'B09PRSTZ8S',
 'B0BS98Z45W',
 'B096ZSQ21B',
 'B09QXLCSV7',
 'B09Q6DJQW8',
 'B09QD14QJV',
 'B0B6691ZJF',
 'B0B5PXSQJQ',
 'B0BPMT98NY',
 'B09PVW2RY1',
 'B09X3C314Q',
 'B0B69WNZFJ',
 'B0B7VNHC85',
 'B0BW2KJK5B',
 'B09Q6CS11V',
 'B0BY32TVLL',
 'B0BK1MP887',
 'B09YYX7NM7',
 'B0BVG575QZ',
 'B0B3JQBWTP',
 'B0B61LKY4C',
 'B0B5LB8B4Z',
 'B0BVRL26XT',
 'B0BJYPTD2C',
 'B09TD8Y4G7',
 'B0BFX868D5',
 'B0B3P4FWHC',
 'B0B4PN8SQF',
 'B0BZDX6749',
 'B0B1F7KWBT',
 'B0BKQJX2Q1',
 'B0B7NPXFFS',
 'B0B7P777HB',
 'B0BKR6V7QK',
 'B0BFWZHS16',
 'B09TVW4VKM',
 'B09SV8DDH1',
 'B09SBZRXFF',
 'B0B8BB1YGC',
 'B0B12M1F7Q',
 'B09QNZ65JC',
 'B09V8F8VF2',
 'B0BRSZDPFF',
 'B0BB5CL39K',
 'B0B5KQMYB5',
 'B0BTB77SZ3',
 'B09TQJ69KH',
 'B0BH1861SR',
 'B0B55D8LLJ',
 'B09WZ34FBT',
 'B0BYL8ZN26',
 'B0BVLC5KPC',
 'B0B4GF4YVK',
 'B0B82GWJVG',
 'B09S6TY2T8',
 'B0B1LYZRY2',
 'B09VX9WGKD',
 'B0BJTL2GD3',
 'B09WRRTHND',
 'B0B6L97TVG',
 'B09N81TM8V',
 'B0C1F4B51R',
 'B09PRMQP5C',
 'B09L97ZB5Y',
 'B0BFRHNMRF',
 'B09N9BFT53',
 'B09R34XHJ6',
 'B09XT4VVP3',
 'B0B4KFSNS2',
 'B0BSTD1BX1',
 'B0BLD2LCYP',
 'B09SP2KT7P',
 'B09X3NHJPT',
 'B0B1BC78VS',
 'B07X1M5S6K',
 'B09ZYHP1XS',
 'B09TNJQMS7',
 'B0B72LLLRN',
 'B0C3F6M8JQ',
 'B09SGWCWHP',
 'B09XF677ZD',
 'B0B5PXSQJH',
 'B0B7XKQ4G1',
 'B0B7271P1G',
 'B0BGYRRMZL',
 'B09XFBZFPX',
 'B09TNCBP23',
 'B0B9HYPYVL',
 'B0B1B9HB7B',
 'B09ZJ64YNW',
 'B09YPXW8VZ',
 'B09T365ZCB',
 'B09V5MS2K3',
 'B0BMT7LLXR',
 'B0B2CJT25B',
 'B09TG4Q9RF',
 'B0B5TFKF9Z',
 'B09V5CQFS8',
 'B0BLJM76J9',
 'B0C3KS9W53',
 'B0B39VNTX1',
 'B0B31XM1JC',
 'B0B7S4BMS5',
 'B0BMQQNLN8',
 'B0B29CBKN2',
 'B0B69WPSGC',
 'B09TPYSGLJ',
 'B0C1ZS6SXL',
 'B0B29MC463',
 'B09XB9M4WW',
 'B09ZKLQPRZ',
 'B0B5RWKP8D',
 'B0C415TN7L',
 'B09TJ4X2QT',
 'B09QNZBV2C',
 'B0B14CH1W6',
 'B0B287C758',
 'B07WSXL21P',
 'B0B2YG2T8N',
 'B09RMBX28F',
 'B00404MBUY',
 'B0BS1RZNB5',
 'B09TMWJ38M',
 'B09TN45G5Y',
 'B000ECX0KQ',
 'B09VL6W7PQ',
 'B0B9HQB1TJ',
 'B0BNGSNSM8',
 'B09WCDCSJG',
 'B0B14HYW73',
 'B0B85KMXKW',
 'B09Q8TWH1H',
 'B0BJCJHBQF',
 'B0BY3VK3Q4',
 'B0B6L2TP2G',
 'B0B2ZCXS1F',
 'B00L2QTQCE',
 'B0BG6SD5DS',
 'B0BHV35JRL',
 'B0B5MCGCS3',
 'B09S2LVL96',
 'B09XBYWNTR',
 'B0BXQ7N549',
 'B099ZPJFZ3',
 'B0C1W5Z6F7',
 'B09XKJNYFL',
 'B09WJ4R345',
 'B09ZLJT349',
 'B0B6XPPPJT',
 'B0BFRJNHLS',
 'B0B7KBZ3HG',
 'B0B15LJPDY',
 'B0BSNSTJYQ',
 'B0B5LS1W9Z',
 'B09VY4TDMZ',
 'B0BHJ75WV5',
 'B09Q3Q2GJL',
 'B0B85VLWH4',
 'B0BY31J6YB',
 'B0C2J9SYDQ',
 'B09QD28ZS1',
 'B09H1FQ35F',
 'B0BDMNBMQW',
 'B0B1B55Q8B',
 'B09S8K9GYR',
 'B0B6XX8TQC',
 'B09VGGZLP3',
 'B0B3M8PDRX',
 'B09NRZM7T7',
 'B0BS71LZCG',
 'B09VT8N62X',
 'B0BCH4427G',
 'B0BX8N6GKK',
 'B09RQWYWZ1',
 'B09TYTDDVB',
 'B0C7HCNFK1',
 'B09MR8SHWN',
 'B0B3PXJKY8',
 'B0BKGM3XB2',
 'B0B69J2QV4',
 'B09WYY8YC6',
 'B09ZCL5PFQ',
 'B09VXYY42K',
 'B09RQZ64PQ',
 'B0B59T3CG8',
 'B09TVFQ6F5',
 'B09QJZL4XM',
 'B0B8MH52Q6',
 'B09VLK12F5',
 'B0B2PZBW3H',
 'B0BS9PGKXJ',
 'B09WRTW258',
 'B09YJ2BYNR',
 'B0B4F8RJCL',
 'B09P3CDB28',
 'B09YVJC3NM',
 'B09VLDGP4Q',
 'B0B4HXKNC7',
 'B09HN59RCM',
 'B0BFJXK8RT',
 'B0BJ7YTZGH',
 'B0BFRF9JPC',
 'B0BCS65PWB',
 'B0B6KJL5XR',
 'B09ZZTRPK9',
 'B0BL1KP2H4',
 'B0BVT4B9DG',
 'B09MTZ67NM',
 'B09MTWT3C1',
 'B0BCX5NPYH',
 'B0B42P37PY',
 'B09QRXY289',
 'B09P229G44',
 'B0BRX3RG8D',
 'B0BJ2ZQ89B',
 'B0BCSB1PWC',
 'B0B8BGB4P5',
 'B0B3C8QMR5',
 'B09XWT51CN',
 'B0BQPY5W9T',
 'B09WNH1ND1',
 'B0BF2L4J9W',
 'B09VWGGQ2S',
 'B09WZ55QSX',
 'B0B6J7W6MJ',
 'B0BWNRYKJK',
 'B0BHF11VMZ',
 'B09V61WQSC',
 'B09RBK5PX3',
 'B0C12T9PK7',
 'B09PK47CGG',
 'B00008EN6G',
 'B0B4BG9GC9',
 'B09WHB35S8',
 'B09Y28VMKB',
 'B09WYRPF69',
 'B0BG62V5J4',
 'B0B3NCVBPK',
 'B09QMKFFHD',
 'B0BFJFN2XK',
 'B09TPRSLJS',
 'B09NH479PK',
 'B0B1F7LLXG',
 'B0BFFRC8CK',
 'B0BBQLH1Z3',
 'B0BM375TYD',
 'B09ZPBGTRB',
 'B09ZHFPB6V',
 'B09XXZPNHG',
 'B09VSCYGLT',
 'B09YBVMX66',
 'B09T8F2ZQF',
 'B09VLCNB1F',
 'B09KP5K928',
 'B0B8GJMCPL',
 'B0B5VXPRWC',
 'B09V4R82C4',
 'B09Y9C87BK',
 'B09X75PHYT',
 'B099ZPJL14',
 'B0B1JF28JM',
 'B0BDMZQNB8',
 'B09X1QY9J7',
 'B09VZDFJPJ',
 'B0B8J6BTJT',
 'B09QH6G31R',
 'B0B44FXM3D',
 'B0B9GZ98CZ',
 'B09QXLFYTW',
 'B09TDVR9DX',
 'B0B753KSWN',
 'B0B3TMYXM4',
 'B09X1TLLNW',
 'B0B4HXF47D',
 'B0BY1J3R2F',
 'B0B5KV672C',
 'B0C36Y7VN5',
 'B0BNYXTH5G',
 'B0BHKWTTR1',
 'B0B7BC3BSZ',
 'B0B53NTZJN',
 'B09QFDYT8P',
 'B09XR6N3ZY',
 'B0B52LQ3DL',
 'B09PVSQMZS',
 'B09T1Q4TL4',
 'B09VFFJ36S',
 'B09VLJFMQZ',
 'B09ZPSS75D',
 'B0BJ1BVM96',
 'B0B92FZQZB',
 'B0BD98S842',
 'B0B4F88T1F',
 'B09XVCPXL1',
 'B0BT89JFKN',
 'B09VWMGHQY',
 'B0BKRX6SJ6',
 'B09WHJ61GB',
 'B09QP1XVJ6',
 'B09YCT4XCL',
 'B0BBRNMGSZ',
 'B0BVDSJLRR',
 'B0B2F94Z8M',
 'B0BPVYN254',
 'B09R2M1ZD2',
 'B07FSRBW5X',
 'B09XBHR521',
 'B0B4KXHVCJ',
 'B0BVZZSB2M',
 'B09PVNF18V',
 'B0BLKF766K',
 'B09Z71WXFD',
 'B0BX8SZ6CY',
 'B09QXBFN7Z',
 'B09PPPGSHD',
 'B09ZCSVZH7',
 'B0BZLDHJR7',
 'B0BWV8Q276',
 'B0C7H6HWWH',
 'B09ZJ54KRT',
 'B09PVHGSRZ',
 'B0B69PC4TP',
 'B09XSJKRHC',
 'B09WPJRSRJ',
 'B09SC1955G',
 'B0073H9BE4',
 'B0BD5WPBVT',
 'B0BL2S3FSL',
 'B0BJVVSLC1',
 'B006ZJTPBA',
 'B0BTXVQ3L1',
 'B003UW1QYY',
 'B0BGY5Y7SN',
 'B09TDPT787',
 'B0B2F2DD5X',
 'B09RG2JX1M',
 'B09PK4WKPV',
 'B0B7XY3JN6',
 'B09WB36XNT',
 'B09NDNP8G5',
 'B0BKT4QT6D',
 'B09TNGZ7FT',
 'B09SP1GQYV',
 'B09Z72LNGJ',
 'B0B4F7FTNW',
 'B09T3S2BTD',
 'B0BL15ZL6L',
 'B0B59SW3J3',
 'B09VY67S6P',
 'B09Q95FVQP',
 'B09WQWCCDM',
 'B0BHJFB321',
 'B09ZTFJ31N',
 'B0BHDTTXZW',
 'B09RX4262T',
 'B0B6Q5LKFH',
 'B0B19R249W',
 'B09SKLJ2HY',
 'B0B1369GCV',
 'B0BQSHS45W',
 'B0B9Y5Z2W9',
 'B09Z6Z4J81',
 'B0BPCZ1N6K',
 'B0BSR2N8Z9',
 'B09V6YJHC9',
 'B09R4RYFXZ',
 'B09RQVG6XD',
 'B0BTB8CDP5',
 'B0B69G23R6',
 'B0B6CG1V5L',
 'B0BWFVZGX5',
 'B0BWS3VLJC',
 'B09XBJ7GXR',
 'B09WXQ6YLR',
 'B0B4VDN9DQ',
 'B0BF361T3D',
 'B0B83SZ37N',
 'B0BJ7ZBVVX',
 'B09VTB9TWF',
 'B09RQZ7S38',
 'B0BCRZSLN7',
 'B09ZYPXH7G',
 'B000MGVBNW',
 'B0BC1DB9VR',
 'B0B4PJ64KC',
 'B0B42Z8VC2',
 'B09Q2DD2PN',
 'B0B9BWS7C6',
 'B0BPMVYL8R',
 'B0BNJQMG9K',
 'B09RG933DR',
 'B09V4CRSXF',
 'B09Q96DW8Q',
 'B0C6R8XB9M',
 'B09S18Q5ZN',
 'B0C55KSG91',
 'B09FC5V9P8',
 'B0BDG9NVYW',
 'B09TRQMB4T',
 'B0BNP1Z8X7',
 'B09T614FYF',
 'B0BMJB42T1',
 'B0BDS12HYD',
 'B09WKPJRMH',
 'B0BQCMT1VR',
 'B09GXK8NZ7',
 'B08N4PDPX5',
 'B0BS1SWPRQ',
 'B09TQ23HPY',
 'B09X3LKKX2',
 'B09Y95Q27X',
 'B0B95VSQ3Y',
 'B09R3JGXYN',
 'B09P5RS352',
 'B09TTSKVXY',
 'B09WGLV528',
 'B09ZPZYNF2',
 'B0BHJFXFS8',
 'B0BFRRZPP8',
 'B000000A04',
 'B0BBB45WHP',
 'B0BC1CXWZM',
 'B0BCBZ2WFN',
 'B09RP62D33',
 'B0BQKRPMF5',
 'B0B59VMMK9',
 'B0BCXGJP5D',
 'B09TTC3H88',
 'B0BJQC5J3D',
 'B09PZJYNW4',
 'B09TPR9L86',
 'B09Z36T854',
 'B0B4D954HM',
 'B0B28FPPKS',
 'B09S6NTFM5',
 'B09Y3LVBLX',
 'B0BS49XTBQ',
 'B0B6CGHW5J',
 'B0BJP8ZBRT',
 'B003SJGS6K',
 'B09TF1J63K',
 'B09Z36QQHB',
 'B0B7BG4LTT',
 'B0BGCD679R',
 'B09SKKHR3Z',
 'B0B9K6VSP8',
 'B09RG79R29',
 'B0BFXBY64H',
 'B09LPD4N45',
 'B0B3GMX2TM',
 'B01LVXUTE4',
 'B0B5LX54RQ',
 'B09QFDVBQ8',
 'B0B3JNCBY7',
 'B09Q97G3RJ',
 'B0C1BF2XRQ',
 'B0B3BBMQ83',
 'B09F1KM8DF',
 'B0BCL4ZR3D',
 'B0BD5RF5J3',
 'B09N94V4LY',
 'B0B2X2JHRP',
 'B09GXZVG8Z',
 'B09JVM4NSP',
 'B0B9Y5BV8G',
 'B09XR5LV4V',
 'B07QN1VF48',
 'B0BC2HT1BY',
 'B0B3Q98TNS',
 'B09PNCR1V2',
 'B0BSXRFQ1D',
 'B0BB5MCBQ9',
 'B0BFRM3DSL',
 'B00005UF1W',
 'B0B5LX4TQQ',
 'B0B7HD8YTV',
 'B09TF66T21',
 'B09SJ3BCLJ',
 'B09RPGVKW7',
 'B09RB33XQB',
 'B0B74SXZ7R',
 'B09WYTW1C2',
 'B09WWGHTR7',
 'B09VFTF8BG',
 'B09ZF4XFYY',
 'B0BG45T5PD',
 'B092491YNZ',
 'B0BNLJSVJL',
 'B0B69G7N57',
 'B0BTR6W3CG',
 'B09V5THY69',
 'B0B7KPHXH6',
 'B09TTLNSKG',
 'B0BS9N7P6X',
 'B0BNZPG7QV',
 'B0B5DWRTP3',
 'B0B7JPWVRF',
 'B09TTMR4WS',
 'B08D4F8NW5',
 'B0BQ3QCSGY',
 'B08L3NWBFN',
 'B09YS6D1VG',
 'B0B9BYBMVS',
 'B0BX4HLCQQ',
 'B0BX1JCW6Q',
 'B09PRQ374Y',
 'B0BCKJQFZ4',
 'B0C1P8PQJ2',
 'B09V3HTH1Y',
 'B0B97ZQZBK',
 'B09MCHK499',
 'B0B9BXZHPK',
 'B09ZF2LQJ2',
 'B0B2PR1SMV',
 'B0B18Z8GL1',
 'B0BDSK1LZQ',
 'B0B1X6B7ZH',
 'B0BG8LSTWV',
 'B09Z6VL26F',
 'B0B71XS6JH',
 'B0B2W13CTW',
 'B0BFXDL5XJ',
 'B09NS1VZJF',
 'B00P0873GG',
 'B0BHJGHWJ7',
 'B09VCS9Q5W',
 'B09SGYNMTL',
 'B00BSWMIOK',
 'B09TW55FY8',
 'B07GGCCW2F',
 'B09M57YCR2',
 'B0BD9FW8B1',
 'B09RMXC83C',
 'B0B98MV1W9',
 'B09XZ2RP29',
 'B09V1PRRP1',
 'B07TKNFWPD',
 'B09X1XR19J',
 'B0BV8FDC3R',
 'B09ZTFMGJQ',
 'B09PNST3BD',
 'B0B34Y36LD',
 'B09X7BFJS1',
 'B09L55RG9H',
 'B09YQF2P9T',
 'B0B2TNC394',
 'B09R3SG6HH',
 'B0BDSHMK4N',
 'B09QS9QT3S',
 'B09QFXHC95',
 'B0B65SZKLJ',
 'B09R3K1T7Y',
 'B09XBN136K',
 'B09Q6DK8VJ',
 'B0B6CH2F2S',
 'B09YNXMG5P',
 'B0B4T2XKWZ',
 'B09PRM1HD4',
 'B09ZHB7C6Z',
 'B091F3JDD5',
 'B09T76VRQ7',
 'B09SJ4JYMY',
 'B09PNMWS9S',
 'B0BCKWP6QH',
 'B0BHJH1WY1',
 'B0BYR861H6',
 'B0B28KVTLD',
 'B09Y282YV6',
 'B0B38ML4JX',
 'B09WPZSL5X',
 'B0BD91TWV5',
 'B09LBZRH23',
 'B09T77S7LT',
 'B0B77HV5S8',
 'B09MDVSW5W',
 'B0BMW24KRP',
 'B09RM5F79W',
 'B0B4WP9GT9',
 'B0C44ZF8Y7',
 'B09SNV6G22',
 'B09Y9G8N94',
 'B09TX45B7J',
 'B0BXXYP7SH',
 'B0BCS7DM3S',
 'B09WRLMLPS',
 'B0BG2QJNR4',
 'B09X222FLZ',
 'B09TB7SZXJ',
 'B09Q6DXCXX',
 'B0BBZFVBYL',
 'B0BH17KRJJ',
 'B0BRXKP2FJ',
 'B0BV5WY5TC',
 'B0B38MQD2H',
 'B09QQS8JXH',
 'B0BM3NHDSL',
 'B0B8P232XQ',
 'B09YNRYM24',
 'B0BT8B6YJS',
 'B09YYWYYLY',
 'B0B18XYVLS',
 'B0BD5VKBBR',
 'B0B42CGTXV',
 'B0BX7CJ8M1',
 'B09YQLN1XN',
 'B09NFQ6593',
 'B09TNT5RYL',
 'B0B15JS7FY',
 'B09ZLQW9ZT',
 'B0BBB56GN3',
 'B0B97LS8V4',
 'B09ZLJV8NK',
 'B09QH11JP7',
 'B09WNGSHJJ',
 'B0C1F6JJVK',
 'B09XY3986D',
 'B0B13Q1S8W',
 'B0B3JV82X4',
 'B09Q3ZS8YV',
 'B09ZLJGLBR',
 'B09WF3XKNW',
 'B09SHT1FZT',
 'B09Q95JPGV',
 'B0B1DBLKK1',
 'B09SP39L9H',
 'B0B3F3JSJ4',
 'B09YHJV4MD',
 'B0B2423WX3',
 'B09P5RSH6P',
 'B09Q6FSSFD',
 'B07Z74RPKK',
 'B0B48WZFDN',
 'B0BTB6DFSW',
 'B0B7KKN5TN',
 'B0BZJ9LCZS',
 'B0B57M2FFK',
 'B0B832LSNC',
 'B09ZCSVY7G',
 'B0BXT2SD5W',
 'B0B5YS5R4J',
 'B09TWMVPJP',
 'B00B66RK6E',
 'B09V5MNY2Q',
 'B0B1BDL91J',
 'B0BJ5XF7FP',
 'B0BBQ739C2',
 'B0BWNMM94H',
 'B0B6GGZMX6',
 'B0BFFXVV76',
 'B09Z829L36',
 'B09TN1SM4L',
 'B0BT88SYXN',
 'B0BCGJQ2FD',
 'B0BM4T45XT',
 'B0BJ966SV7',
 'B01DXT208Y',
 'B0BVDX1HQ9',
 'B09XBGM4GB',
 'B0BDFW4VRB',
 'B0BHL7XS7N',
 'B09QF44KNV',
 'B0BY3RN2LY',
 'B0B5HNCBRK',
 'B0BM4WHYYK',
 'B0BYHFG53W',
 'B0B4KB7R8N',
 'B0B3WFFR82',
 'B09XR59891',
 'B092J9RM4K',
 'B0BNGSR77M',
 'B09J5H7VZQ',
 'B0B69WNM58',
 'B09WLCQWN6',
 'B0B5221X8Q',
 'B09WGR2M18',
 'B09X1WGNZX',
 'B0BS8ZD6LV',
 'B09RPYV9SD',
 'B0B61QJB1B',
 'B013BXK65G',
 'B0B2ZRV4FD',
 'B0C1W8D88H',
 'B0C2B869LV',
 'B0B2F4QHZ1',
 'B0B8P3G6X8',
 'B0B7VQQB7Q',
 'B0BS1TL5FY',
 'B0B6J9GBZT',
 'B07D4ZPJPC',
 'B087L6RMM6',
 'B0B3M4DFWL',
 'B09MVH85ZP',
 'B0B17K7HBN',
 'B09M527FC6',
 'B09PMFYFN4',
 'B0BVZQ14TF',
 'B09X1WHSM6',
 'B09X69JHKJ',
 'B004GHYC5W',
 'B09SJ2PC8J',
 'B09V5FB1KP',
 'B0B75289L8',
 'B0B1232NCL',
 'B09TS84LC3',
 'B0BFFGH7NW',
 'B0B16MH5V5',
 'B09QMQX7VR',
 'B09ZJ6LM5P',
 'B09YHBG79B',
 'B09T8WF9NW',
 'B0B44VMJSF',
 'B0854GHBF1',
 'B09YMGSZ46',
 'B0B5FVDZCM',
 'B09RPHV5PH',
 'B09TQBLD8C',
 'B09TDS2389',
 'B0B92G12Z7',
 'B0BM4SSKCS',
 'B0B78DXM3H',
 'B09V5HB2GH',
 'B0BZV1DCLX',
 'B0BFRRJCG7',
 'B0B1ZZGPKT',
 'B0B79PKP83',
 'B0BS1R6Z5V',
 'B0B4BNT7GR',
 'B0B57PDQWP',
 'B09QVW4H3B',
 'B09QNNDJP3',
 'B09QWC45BK',
 'B09T6ZDPF4',
 'B09XRFCZ8M',
 'B0BL15XJSW',
 'B09XVCWQGL',
 'B0B7BV8CNT',
 'B09X77QRCC',
 'B09TWRFSDJ',
 'B09Y6C9B8V',
 'B0BTB7LMM9',
 'B09XBNRXHZ',
 'B0B3HL8HV1',
 'B0B46X16BS',
 'B00NBXVL9M',
 'B09PRL5931',
 'B09K34PWGC',
 'B09P5QPP1L',
 'B0BFJV3NHK',
 'B0B1J38Q6S',
 'B0BWFSTNRM',
 'B09V5P217G',
 'B0B2LZSWHR',
 'B09XKL7P4M',
 'B09QF77TMC',
 'B0B29F3YGM',
 'B09SK4C3W3',
 'B0BBSBZ59F',
 'B09VH796Y7',
 'B0BF5LXMHZ',
 'B09QMKMGMR',
 'B09T2X55VG',
 'B0BY9MQL3M',
 'B0B3S2GHFX',
 'B0B5R7C53Q',
 'B09Y3HQLT4',
 'B09TJ4L1GG',
 'B0BL8QZYDG',
 'B09X8JSJ1L',
 'B0BKLP5B2Q',
 'B09ZCQTQX9',
 'B0BH3R9D4X',
 'B0BBZ2DPMJ',
 'B0BJ9BHSK8',
 'B0BL3PK2V6',
 'B0BBSG3C74',
 'B09Q3NP1LH',
 'B0BFRHNX8X',
 'B0BTRMTN9X',
 'B0BBRQYNQH',
 'B09PZKN1FC']

#### load amazon reviews dataset

In [10]:
df_reviews=pd.read_json("../../data/CDs_and_Vinyl_2022_2023_with_category_ratings_10_sample_1000.jsonl",lines=True)

In [11]:
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,4,"If this is rock 'n' roll retirement, I'll take...","Yet again, David Crosby keeps the winning stre...",[],B0BH3R9D4X,B0BH3R9D4X,AE7BV6IMNPZ3F266H7PXMH3BZQNQ,2023-01-08 22:56:15.968,8,True
1,4,"CCR's legendary 1970 Royal Albert Hall gig, fi...",CCR's legendary 1970 Royal Albert Hall concert...,[],B0B18Z8GL1,B0B18Z8GL1,AE7BV6IMNPZ3F266H7PXMH3BZQNQ,2022-09-16 18:05:34.559,21,True
2,3,Songs for Beginners / Wild Tales 50 + years do...,So many 5-star reviews. I just don't get it. ...,[],B09VCS9Q5W,B09VCS9Q5W,AE7BV6IMNPZ3F266H7PXMH3BZQNQ,2022-06-03 20:56:32.958,4,True
3,4,A master lesson from a pair of legends,Mavis and Levon. Staples and Helm. If you're...,[],B09VLCNB1F,B09VLCNB1F,AE7BV6IMNPZ3F266H7PXMH3BZQNQ,2022-05-22 15:32:49.839,9,True
4,3,"Disappointing, at best","Musically and vocally, Van's still the man. B...",[],B09V4R82C4,B09V4R82C4,AE7BV6IMNPZ3F266H7PXMH3BZQNQ,2022-05-22 15:03:02.428,1,True

In [12]:
len(df_reviews)

8721

In [13]:
df_reviews_sample=df_reviews[df_reviews["parent_asin"].isin(parent_asin_list)]

In [14]:
len(df_reviews_sample)

8721

#### define funtions to preprocess reviews data

In [15]:
def preprocess_reviews_data(row):
    return f"{row['title']} {row['text']}"

In [16]:
encoding=tiktoken.encoding_for_model("text-embedding-3-small")

In [17]:
encoding.encode("Can I get some earphones")

[6854, 358, 636, 1063, 2487, 17144]

In [18]:
def token_count(row,model="text-embedding-3-small"):
    encoding=tiktoken.encoding_for_model(model)
    return len(encoding.encode(row["preprocessed_data"]))

In [19]:
df_reviews_sample["preprocessed_data"]=df_reviews_sample.apply(preprocess_reviews_data,axis=1)

In [20]:
df_reviews_sample["preprocessed_data_token_count"]=df_reviews_sample.apply(token_count,axis=1)

In [21]:
df_reviews_sample.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,preprocessed_data,preprocessed_data_token_count
0,4,"If this is rock 'n' roll retirement, I'll take...","Yet again, David Crosby keeps the winning stre...",[],B0BH3R9D4X,B0BH3R9D4X,AE7BV6IMNPZ3F266H7PXMH3BZQNQ,2023-01-08 22:56:15.968,8,True,"If this is rock 'n' roll retirement, I'll take...",210
1,4,"CCR's legendary 1970 Royal Albert Hall gig, fi...",CCR's legendary 1970 Royal Albert Hall concert...,[],B0B18Z8GL1,B0B18Z8GL1,AE7BV6IMNPZ3F266H7PXMH3BZQNQ,2022-09-16 18:05:34.559,21,True,"CCR's legendary 1970 Royal Albert Hall gig, fi...",321
2,3,Songs for Beginners / Wild Tales 50 + years do...,So many 5-star reviews. I just don't get it. ...,[],B09VCS9Q5W,B09VCS9Q5W,AE7BV6IMNPZ3F266H7PXMH3BZQNQ,2022-06-03 20:56:32.958,4,True,Songs for Beginners / Wild Tales 50 + years do...,355
3,4,A master lesson from a pair of legends,Mavis and Levon. Staples and Helm. If you're...,[],B09VLCNB1F,B09VLCNB1F,AE7BV6IMNPZ3F266H7PXMH3BZQNQ,2022-05-22 15:32:49.839,9,True,A master lesson from a pair of legends Mavis a...,117
4,3,"Disappointing, at best","Musically and vocally, Van's still the man. B...",[],B09V4R82C4,B09V4R82C4,AE7BV6IMNPZ3F266H7PXMH3BZQNQ,2022-05-22 15:03:02.428,1,True,"Disappointing, at best Musically and vocally, ...",90

In [22]:
len(df_reviews_sample)

8721

In [23]:
df_reviews_sample=df_reviews_sample[df_reviews_sample["preprocessed_data_token_count"]<8192]

In [24]:
len(df_reviews_sample)

8721

In [25]:
total_tokens=df_reviews_sample["preprocessed_data_token_count"].sum()

In [26]:
total_tokens

np.int64(562054)

#### create a new Qdrant Collection for reviews

In [27]:
qdrant_client.create_collection(
    collection_name="amazon-items-collection-02-openai-small-reviews",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE),
)

UnexpectedResponse: Unexpected Response: 409 (Conflict)
Raw response content:
b'{"status":{"error":"Wrong input: Collection `amazon-items-collection-02-openai-small-reviews` already exists!"},"time":0.000401292}'

In [28]:
qdrant_client.create_payload_index(
    collection_name="amazon-items-collection-02-openai-small-reviews",
    field_name="parent_asin",
    field_schema=PayloadSchemaType.KEYWORD
)

UpdateResult(operation_id=4, status=<UpdateStatus.COMPLETED: 'completed'>)

#### embedding functions

In [29]:
def get_embedding(text, model="text-embedding-3-small"):
    response=openai.embeddings.create(
        input=[text],
        model=model,
    )
    return response.data[0].embedding

In [30]:
def get_embedding_batch(text_list, model="text-embedding-3-small",batch_size=100):
    if len(text_list)<=batch_size:
        response=openai.embeddings.create(
            input=text_list,
            model=model,
        )
        return [item.embedding for item in response.data]

    all_embeddings=[]
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch=text_list[i:i+batch_size]
        response=openai.embeddings.create(
            input=batch,
            model=model,
        )
        all_embeddings.extend([item.embedding for item in response.data])
        print(f"Processed batch {counter} of {len(text_list)//batch_size + 1}")
        counter += 1
    return all_embeddings

#### embed the text and add additional fields to the payload of each vector for reviews

In [31]:
data_to_embed_reviews=df_reviews_sample[["preprocessed_data","parent_asin"]].to_dict(orient="records")

In [32]:
data_to_embed_reviews

[{'preprocessed_data': 'If this is rock \'n\' roll retirement, I\'ll take it! Yet again, David Crosby keeps the winning streak alive.  Live at the Capitol Theatre.  Incredibly, and against all kinds of odds, Croz has outlasted and outpaced (with the possible exception of Chris Hillman) all of his former Byrds and CSN (&Y) bandmates since crossing over into the new millennium.  And don\'t forget "& the Lighthouse Band."  This is a group effort, and it\'s a solid one.  Covering material from across Crosby\'s storied career, with a definite accent on the more recent works, Live at the Capitol is aural technicolor dream, a kind of band biography in song.  Don\'t know if you had to be there, or not -- I wasn\'t -- but you\'ll feel like you\'re right there in the audience whether listening to the CD or watching and listening to the DVD.  Very impressive live album.  Four shining stars and definitely recommended.',
  'parent_asin': 'B0BH3R9D4X'},
 {'preprocessed_data': "CCR's legendary 1970 Royal Albert Hall gig, finally CCR's legendary 1970 Royal Albert Hall concert arrives, finally.  Thirty plus years ago the first version was released and later found to be labelled incorrectly, it was actually an Oakland, CA date.  Great show, regardless.  There was also the Live in Europe release, but that was CCR trio style, the band minus Tom Fogerty.  Still, a rockin' good time for hardcore Creedence fans.  CCR at Woodstock followed after decades of John Fogerty saying it wasn't a worthy enough show for record release.  Turns out it was actually excellent.  Now, here we are at The Royal Albert Hall, and it all seems rather anticlimactic, sadly.  The setlist is pretty much in line with The Concert disc (Oakland), and not much different than the trio record or the Woodstock show.  The refurbished sound is excellent (thank you, Giles Martin), the band is in its usual fine form from the day, and the British audience appears to be really into the performance.  It just seems a bit too late and all too familiar following on the heels of the other 'live' CCR releases.  Makes for one big 'what might have been' moment.  Blame it on poor scheduling and the never-ending passage of time, but I can only give four fading stars to what should have been a five-star review.  Recommended to diehard CCR fans and to those who don't already have the other three live-in-concert discs.",
  'parent_asin': 'B0B18Z8GL1'},
 {'preprocessed_data': "Songs for Beginners / Wild Tales 50 + years down the line So many 5-star reviews.  I just don't get it.  I've been a faithful CSN (if less so CSNY) fan since plunking down hard-earned summer job money for Crosby, Stills & Nash back in 1969.  Hooked, I've been a CSN completist ever since.  Even after the trio -- in a very foolhardy turn of events -- painted themselves into a corner, or into the background really, and were rather cruelly referred to as Neil Young's backing singers, I kept on buying.  CSN.  CSNY.  Solo C.  Solo S.  Solo N.  Often solo Y.  C-N.  Manassas.  S-Y Band.  Got 'em all, except some of Neil's new millennium releases.  Crosby, Stills and Nash is a 5-star album, as are Manassas, After the Gold Rush, Wind on the Water.  Songs for Beginners?  Three and a half stars.  Wild Tales?  Three stars.  This live-in-concert presentation of those two LPs is a 3-star release, at best, basically a pleasant if non-essential concert memento.  Fine band, good to very good songs, solid arrangements.  Unfortunately, Nash's 80-year-old vocals have begun to show the wear and tear of the intervening 50-plus years.  I'd have preferred a remixed / remastered two-fer containing the original albums (which I still listen to on my old Atlantic Records LPs).  Recommended for diehard Nash fans and CSN completists only (like myself).",
  'parent_asin': 'B09VCS9Q5W'},
 {'preprocessed_data': "A master lesson from a pair of legends Mavis and Levon.  Staples and Helm.  If you're even remotely interested in that pairing of truly legendary performers, well, you don't need me to go blathering on about how great it is.  Which it is -- great!  A master class in singing and performing.  The sound isn't always all I would've hoped for, and the liner notes are a bit on the scant side.  But the setlist is pure joy and the performances raise the roof like a heavenly revival throughout.  Highly recommended.",
  'parent_asin': 'B09VLCNB1F'},
 {'preprocessed_data': "Disappointing, at best Musically and vocally, Van's still the man.  But oh, those lyrics!  The kindest thing I can say?  Disappointing, and in a big way.  Love the front cover graphics (Invasion of the Body Snatchers), although I'd have to say it's theme cuts a bit too close to the albums vapid lyrical content.  Three pods from me.",
  'parent_asin': 'B09V4R82C4'},
 {'preprocessed_data': 'Did anyone else just get the sleeve? Am I the only one who purchased this record only to receive just the sleeve and no actual record to be found! Sad, it’s a damn good album and I would’ve liked to hear it on my player',
  'parent_asin': 'B09LBZRH23'},
 {'preprocessed_data': "Bought as gifts I bought a couple of these as Christmas gifts. My friends loved them and said that they played them daily on their commutes etc. Everyone likes Dolly's music, you can't go wrong with this as a gift.",
  'parent_asin': 'B0BBSG3C74'},
 {'preprocessed_data': 'George Winston\'s Newest I\'ve been listening to George Winston since I saw a space special on the old Disney Channel (you know, the one that actually showed Disney programming and not Marvel and STAR WARS) which featured his piece "Moon." I still love Winston, but I admit I do not like his newer albums as much as the originals. I was fond of his piano pieces and the slack guitar just doesn\'t do it for me. I can\'t think of any selection here that really caught my ear, but the album was pleasing and I will continue to buy his work.',
  'parent_asin': 'B09SJ3BCLJ'},
 {'preprocessed_data': 'OMG my kids and I LOVE THIS! OMG my kids and I LOVE THIS!!! i purchased 2 other videos of theirs and a CD. Love them all!!! My 2 year old loves them also!!! Will sit still and watch and sing along! LOVE LOVE LOVE THIS !!',
  'parent_asin': 'B003SJGS6K'},
 {'preprocessed_data': "Harlem River Blues Justin Townes Earle I do enjoy Justin Townes Earle's music and have found after a couple of CDs that the more I listen to him and his band, the more I like him. Good for me and him.",
  'parent_asin': 'B003UW1QYY'},
 {'preprocessed_data': 'Best Album Yet! I am a huge Miranda Lambert fan! This is in my opinion, her best album so far. Every single song will be a hit I am sure!',
  'parent_asin': 'B09V5MNY2Q'},
 {'preprocessed_data': "Nostalgic, Exciting, Sad This is my first comeback. All of the eras represented in these three discs are still fresh to me, and because I only started listening a year ago, the group’s development as artists is obvious to me.<br /><br />I shouldn’t feel nostalgic.<br /><br />So why am I crying?<br /><br />The news that they're taking a hiatus was not that unexpected. They've devoted so much of their young adulthood to the group and to their fans, plus the pandemic has kept them on uncertain ground that it's hard to adjust to when seven have to move the same way at the same time. So, that's hard, but not why I cry.<br /><br />Gratitude, maybe? The anthology songs they chose include a solo stage and a favorite OT7 song picked by each. Their thoughtfulness aside, BTS is a group that always has a message for their listeners. It can be broadly about social justice (No More Dream) or about a specific event (Spring Day, the melody of which uses genius changes to evoke the loss of innocence and friends - and uses the simple refrain I miss you I miss you to break your heart).<br /><br />Maybe there’s a little trepidation? Yet To Come, one of the three new songs and the only one so far to have a video, is light and poppie and assures us all that there’s more. But the video heavily references not only their past music videos but also a specific performance video of Life Goes On. And forward motion is good, right? But the best moment is yet to come is a statement that asks a lot of trust of the listener. Particularly when the past is as good as theirs.<br /><br />And the kind of trust it asks for is a jumping into the void/letting go kind of trust. Especially when the passage of time affects their obligations to their home country and their physical ability to continue doing the pyrotechnic choreography that made them that much better- on top of lyricism, social accountability, and reciprocal concern for their fandom - but, yeah, the athleticism has been outstanding.<br /><br />I think that may be the answer to why I am crying. They’re clearly drawing a line between then and what’s next. If they eventually get back together to perform in concerts, it won't be what it was before.<br /><br />Musically, there’s nothing to cry about, unless it’s tears of thankfulness. Instead of just a greatest hits compilation, they’ve added three new songs and a disc full of demos. Clever men, they share with us unpolished versions of themselves while answering the bitter critics who (falsely) allege that the members do not actually write.<br /><br />So, whatever comes next, we are assured that the smack talk and clap back will continue. Plus the bop.<br /><br />Run BTS is an upbeat number with a groove that begs for choreography. For Youth references all of the sweet songs and the not so sweet ones about innocence and, to an extent, power disparities in an inherently unjust world. There is nothing about this song that suggests BTS is going to stop trying to make the world a better place.<br /><br />The record merits multiple listen. Even if you know the old songs well, hearing them in this new context will reveal more. And I dare you not to make it move left and right.<br /><br />Notes: Disc 2's OST/OT7 picks go in fan chant order. And the standard edition weighs a ton -> SO many pages in the books. Gorgeous photos.<br /><br />Highly recommend. Thank you, BTS, Big Hit, HYBE.",
  'parent_asin': 'B09ZF2LQJ2'},
 {'preprocessed_data': "a nice addition to my collection who doesn't love Dolly Parton!!!!",
  'parent_asin': 'B0BBSG3C74'},
 {'preprocessed_data': "Sounds like Behemoth This is a decent album, but doesn't stand out.  It'll get listened to from time to time.",
  'parent_asin': 'B0B1369GCV'},
 {'preprocessed_data': 'Five Stars Another great compilation by Coco Montoya!',
  'parent_asin': 'B01N7VL812'},
 {'preprocessed_data': "Love it This CD has various singers on it, not just Ashley.  If you are a fan of Jerry Jeff Walker, you will love this CD.  I'm very happy with the purchase.",
  'parent_asin': 'B0BCH4427G'},
 {'preprocessed_data': 'Best album yet! I love every song on this album!',
  'parent_asin': 'B09VLK12F5'},
 {'preprocessed_data': "Great CD by Ozzy. I gave this as a gift for Christmas, but I also received one the same day.  Love the music.  One of Ozzy's better CDs.  A couple of the songs sound a bit similar to ones he put out about 10 years ago.",
  'parent_asin': 'B0B4KXHVCJ'},
 {'preprocessed_data': 'super concert 100 0/0 cover and booklet came wet? CD /super concert 100 0/0 cover and booklet came wet?',
  'parent_asin': 'B09TS84LC3'},
 {'preprocessed_data': 'Awesome record This is a great record at a great price!',
  'parent_asin': 'B09PNQZHH2'},
 {'preprocessed_data': 'Blasphemy! Yeah I held off on getting this awhile. I thought it an unnecessary remix of a perfect, beautifully evil album that I have adored forever, held in a special place in my heart, and I was having none of it. How dare you! Money grabbers!<br /><br />I was wrong wrong wrong. Amazon kept shoving it in my face as a recommendation, as something I might wanna buy. And kept going “blehh” no I don’t, no YOU don’t, Al Gorhythm, and no I won’t!<br /><br />But I finally gave it a glancing preview of a listen, and noticed a few little things like roaring controlled guitar flourishes, keyboards that sounded like the guy from Wish You Were Here was  actually playing on this record, Roger Waters sounding clear and vulnerable, and one of the most underrated drummers of our time finally getting his due.',
  'parent_asin': 'B0B4KFSNS2'},
 {'preprocessed_data': 'Get If you get just one re-release with extra live stuff, this is it.<br />It makes Exit irrelevant; Camera Eye and Red Barchetta are pure joy.<br />Geddy likely didn’t believe at the time this was going to be a live record, so he is loose but tight, in a good way, not striving so hard for that famous Rush perfection we are all so familiar with. And they know MP is THE record, this is THE tour, they’re on their way up like a rocket, and they sound like it.<br />The percussion is sooo good, it makes me wanna cry.',
  'parent_asin': 'B09SGYNMTL'},
 {'preprocessed_data': 'Very disappointing. Check out other albums, “Into The Silent Planet” and “Gretchen Goes to Nebraska” These guys are great writers and musicians when it come to rock. They have the harmonies of The Beatles and the punch of Led Zeppelin but this latest album lacks both of those sounds. They’ve recorded over 15 albums which I own but this one is a stinker. Go on YouTube and listen to “We We’re Born To Be Loved”, “Dogman”, “Lost In Germany” and “Goldilocks” for some great rock samples..',
  'parent_asin': 'B0B5221X8Q'},
 {'preprocessed_data': 'I needed a newer copy of this album So glad they still produce vinyl records, my previous version of this album was damaged, so this is a replacement.  Price is too high for me, personally, but I really wanted to listen to this again.',
  'parent_asin': 'B0BFFXVV76'},
 {'preprocessed_data': 'A must buy Elvin Bishop has such a great voice and sings like he telling a story, most of which are funny, I love this cd',
  'parent_asin': 'B00L2QTQCE'},
 {'preprocessed_data': 'Straight from the documentary! Did you love the documentary, but wanted the music too?!  Well, here ya go!  Sounds FANTASTIC!',
  'parent_asin': 'B09WNGSHJJ'},
 {'preprocessed_data': 'call me if you get lost album My teen loves this album',
  'parent_asin': 'B09FC5V9P8'},
 {'preprocessed_data': 'Awesome 👏 I love ❤️ It. Can’t wait to see him again.',
  'parent_asin': 'B09R3K1T7Y'},
 {'preprocessed_data': 'good stuff listen to it. music to tap your foot to.',
  'parent_asin': 'B00005UF1W'},
 {'preprocessed_data': 'This ain\'t Rush, this ain\'t Rush Lite, this ain\'t Victor... this is Envy of None! ... and this IS a great album! Those naysayers whining that this doesn\'t sound like Rush have obviously not been paying attention... Rush as an entity putting out new music doesn\'t exist anymore. This isn\'t Alex and Geddy and some Neil wannabe. This is Alex and Alf and Andy and Maiah.  This album is atmospheric and ethereal and moody. There are touches here and there that clue you into Alex\'s presence, especially the opening to "Spy House". But Alex has made It abundantly clear that this isn\'t a solo recording... this it a band/collaboration project with all 4 members bringing stuff to the table.  Sit alone, in the dark, perhaps while driving, and listen to this music... it\'s captivating.',
  'parent_asin': 'B09Q97G3RJ'},
 {'preprocessed_data': "Blues is a rocking! Started with the Alligator Records 40th Anniversary Collection and now have this 45th and just bought and waiting on the 35th.  I don't know that i have ever had any multi-cd i have bought give me so many great songs throughout the cd's.  If you like a more bluesy but at times rocking mix of music this (and the others) are great to have in your collection.  Love the music, just wish it wasn't every 5 years!!!!",
  'parent_asin': 'B01DXT208Y'},
 {'preprocessed_data': "Great compilation I am not a professional product rater such as appears on Amazon so much (are they paid by companies to do this?), just a regular person.  As such I am not going to tell you every little detail about this compilation, one because I don't have the time and 2 because why don't you just listen to it.  But I will say this has been one of the more enjoyable purchases of music i have made in the last few years and if you are a music lover and like this type of music you won't go wrong buying this.",
  'parent_asin': 'B004GPEB50'},
 {'preprocessed_data': "Why? I'm a huge Dolly fan, but I'm left befuddled at why yet another Greatest Hits album is needed.  There are seemingly dozens of them already, and real Dolly fans already have these tracks.  Odd.",
  'parent_asin': 'B09QY26Q9P'},
 {'preprocessed_data': "Nothing New Here If you're a Madonna fan, you've heard these versions untold times already.  Even if some are slightly different, you're more than familiar with the tunes.  As in the case with most Madonna songs, these have been remixed and rehashed plenty of times before, when they were first released.  Save your money if you don't already have a free streaming service and listen to half of these songs in their original versions.  The other half (the later years' songs) are trash anyway.",
  'parent_asin': 'B09ZHFPB6V'},
 {'preprocessed_data': "Big fan, new and old. Yes it's different than the old stuff, does not mean it's bad. Music is all about how you feel when you listen to it and this is really good.",
  'parent_asin': 'B0B79PKP83'},
 {'preprocessed_data': 'Great CD Great CD', 'parent_asin': 'B0B4KXHVCJ'},
 {'preprocessed_data': "Larry McCray rocks. We watched Larry McCray perform at Friday Night Live in Saginaw, Michigan and we were amazed at his talent. This guy should be up there with the other Blues legends. I bought the CD for my husband's birthday and he LOVES it.",
  'parent_asin': 'B09Q6DK8VJ'},
 {'preprocessed_data': 'The best thrash album this year! Holy crap!  This album just annihilates.  These guys just rocketed up from virtually unknown to the top of the thrash heap.  This album verges on the edge of total chaos, but it so tight.  I saw these guys live about 2 months ago and it was one of the best gigs I ever was at.  And I’ve been to over 300.  I don’t know how they pull off these insane riffs at those speeds without sounding sloppy.<br /><br />The only negative thing about this album is that it is only an EP.  We want more!',
  'parent_asin': 'B09PVW2RY1'},
 {'preprocessed_data': 'Excellent Return to Form Skid Row is BACK! I doubt there will be any better hard/classic rock release this year. The highlight, as every other reviewer as proclaimed, is Eric Gronwall\'s vocals. He\'s everything Sebastian ever was and has his own style to boot. These tracks are classic Skid Row but aren\'t dated either so whether you\'re an original fan of the band or new to the party, you\'ll appreciate The Gang\'s All Here. The first couple of tracks are attention-getters, but I recommend "October\'s Song" too-more of an epic. "Time Bomb" is a good track, but who else remembers Saliva\'s 2001 hit "Tick Tick Boom?" Skid Row owes them.<br /><br />I repeat, Highly Recommended.',
  'parent_asin': 'B09VZH5B2R'},

In [33]:
text_to_embed_reviews=[item["preprocessed_data"] for item in data_to_embed_reviews]

In [34]:
text_to_embed_reviews

['If this is rock \'n\' roll retirement, I\'ll take it! Yet again, David Crosby keeps the winning streak alive.  Live at the Capitol Theatre.  Incredibly, and against all kinds of odds, Croz has outlasted and outpaced (with the possible exception of Chris Hillman) all of his former Byrds and CSN (&Y) bandmates since crossing over into the new millennium.  And don\'t forget "& the Lighthouse Band."  This is a group effort, and it\'s a solid one.  Covering material from across Crosby\'s storied career, with a definite accent on the more recent works, Live at the Capitol is aural technicolor dream, a kind of band biography in song.  Don\'t know if you had to be there, or not -- I wasn\'t -- but you\'ll feel like you\'re right there in the audience whether listening to the CD or watching and listening to the DVD.  Very impressive live album.  Four shining stars and definitely recommended.',
 "CCR's legendary 1970 Royal Albert Hall gig, finally CCR's legendary 1970 Royal Albert Hall concert arrives, finally.  Thirty plus years ago the first version was released and later found to be labelled incorrectly, it was actually an Oakland, CA date.  Great show, regardless.  There was also the Live in Europe release, but that was CCR trio style, the band minus Tom Fogerty.  Still, a rockin' good time for hardcore Creedence fans.  CCR at Woodstock followed after decades of John Fogerty saying it wasn't a worthy enough show for record release.  Turns out it was actually excellent.  Now, here we are at The Royal Albert Hall, and it all seems rather anticlimactic, sadly.  The setlist is pretty much in line with The Concert disc (Oakland), and not much different than the trio record or the Woodstock show.  The refurbished sound is excellent (thank you, Giles Martin), the band is in its usual fine form from the day, and the British audience appears to be really into the performance.  It just seems a bit too late and all too familiar following on the heels of the other 'live' CCR releases.  Makes for one big 'what might have been' moment.  Blame it on poor scheduling and the never-ending passage of time, but I can only give four fading stars to what should have been a five-star review.  Recommended to diehard CCR fans and to those who don't already have the other three live-in-concert discs.",
 "Songs for Beginners / Wild Tales 50 + years down the line So many 5-star reviews.  I just don't get it.  I've been a faithful CSN (if less so CSNY) fan since plunking down hard-earned summer job money for Crosby, Stills & Nash back in 1969.  Hooked, I've been a CSN completist ever since.  Even after the trio -- in a very foolhardy turn of events -- painted themselves into a corner, or into the background really, and were rather cruelly referred to as Neil Young's backing singers, I kept on buying.  CSN.  CSNY.  Solo C.  Solo S.  Solo N.  Often solo Y.  C-N.  Manassas.  S-Y Band.  Got 'em all, except some of Neil's new millennium releases.  Crosby, Stills and Nash is a 5-star album, as are Manassas, After the Gold Rush, Wind on the Water.  Songs for Beginners?  Three and a half stars.  Wild Tales?  Three stars.  This live-in-concert presentation of those two LPs is a 3-star release, at best, basically a pleasant if non-essential concert memento.  Fine band, good to very good songs, solid arrangements.  Unfortunately, Nash's 80-year-old vocals have begun to show the wear and tear of the intervening 50-plus years.  I'd have preferred a remixed / remastered two-fer containing the original albums (which I still listen to on my old Atlantic Records LPs).  Recommended for diehard Nash fans and CSN completists only (like myself).",
 "A master lesson from a pair of legends Mavis and Levon.  Staples and Helm.  If you're even remotely interested in that pairing of truly legendary performers, well, you don't need me to go blathering on about how great it is.  Which it is -- great!  A master class in singing and performing.  The sound isn't always all I would've hoped for, and the liner notes are a bit on the scant side.  But the setlist is pure joy and the performances raise the roof like a heavenly revival throughout.  Highly recommended.",
 "Disappointing, at best Musically and vocally, Van's still the man.  But oh, those lyrics!  The kindest thing I can say?  Disappointing, and in a big way.  Love the front cover graphics (Invasion of the Body Snatchers), although I'd have to say it's theme cuts a bit too close to the albums vapid lyrical content.  Three pods from me.",
 'Did anyone else just get the sleeve? Am I the only one who purchased this record only to receive just the sleeve and no actual record to be found! Sad, it’s a damn good album and I would’ve liked to hear it on my player',
 "Bought as gifts I bought a couple of these as Christmas gifts. My friends loved them and said that they played them daily on their commutes etc. Everyone likes Dolly's music, you can't go wrong with this as a gift.",
 'George Winston\'s Newest I\'ve been listening to George Winston since I saw a space special on the old Disney Channel (you know, the one that actually showed Disney programming and not Marvel and STAR WARS) which featured his piece "Moon." I still love Winston, but I admit I do not like his newer albums as much as the originals. I was fond of his piano pieces and the slack guitar just doesn\'t do it for me. I can\'t think of any selection here that really caught my ear, but the album was pleasing and I will continue to buy his work.',
 'OMG my kids and I LOVE THIS! OMG my kids and I LOVE THIS!!! i purchased 2 other videos of theirs and a CD. Love them all!!! My 2 year old loves them also!!! Will sit still and watch and sing along! LOVE LOVE LOVE THIS !!',
 "Harlem River Blues Justin Townes Earle I do enjoy Justin Townes Earle's music and have found after a couple of CDs that the more I listen to him and his band, the more I like him. Good for me and him.",
 'Best Album Yet! I am a huge Miranda Lambert fan! This is in my opinion, her best album so far. Every single song will be a hit I am sure!',
 "Nostalgic, Exciting, Sad This is my first comeback. All of the eras represented in these three discs are still fresh to me, and because I only started listening a year ago, the group’s development as artists is obvious to me.<br /><br />I shouldn’t feel nostalgic.<br /><br />So why am I crying?<br /><br />The news that they're taking a hiatus was not that unexpected. They've devoted so much of their young adulthood to the group and to their fans, plus the pandemic has kept them on uncertain ground that it's hard to adjust to when seven have to move the same way at the same time. So, that's hard, but not why I cry.<br /><br />Gratitude, maybe? The anthology songs they chose include a solo stage and a favorite OT7 song picked by each. Their thoughtfulness aside, BTS is a group that always has a message for their listeners. It can be broadly about social justice (No More Dream) or about a specific event (Spring Day, the melody of which uses genius changes to evoke the loss of innocence and friends - and uses the simple refrain I miss you I miss you to break your heart).<br /><br />Maybe there’s a little trepidation? Yet To Come, one of the three new songs and the only one so far to have a video, is light and poppie and assures us all that there’s more. But the video heavily references not only their past music videos but also a specific performance video of Life Goes On. And forward motion is good, right? But the best moment is yet to come is a statement that asks a lot of trust of the listener. Particularly when the past is as good as theirs.<br /><br />And the kind of trust it asks for is a jumping into the void/letting go kind of trust. Especially when the passage of time affects their obligations to their home country and their physical ability to continue doing the pyrotechnic choreography that made them that much better- on top of lyricism, social accountability, and reciprocal concern for their fandom - but, yeah, the athleticism has been outstanding.<br /><br />I think that may be the answer to why I am crying. They’re clearly drawing a line between then and what’s next. If they eventually get back together to perform in concerts, it won't be what it was before.<br /><br />Musically, there’s nothing to cry about, unless it’s tears of thankfulness. Instead of just a greatest hits compilation, they’ve added three new songs and a disc full of demos. Clever men, they share with us unpolished versions of themselves while answering the bitter critics who (falsely) allege that the members do not actually write.<br /><br />So, whatever comes next, we are assured that the smack talk and clap back will continue. Plus the bop.<br /><br />Run BTS is an upbeat number with a groove that begs for choreography. For Youth references all of the sweet songs and the not so sweet ones about innocence and, to an extent, power disparities in an inherently unjust world. There is nothing about this song that suggests BTS is going to stop trying to make the world a better place.<br /><br />The record merits multiple listen. Even if you know the old songs well, hearing them in this new context will reveal more. And I dare you not to make it move left and right.<br /><br />Notes: Disc 2's OST/OT7 picks go in fan chant order. And the standard edition weighs a ton -> SO many pages in the books. Gorgeous photos.<br /><br />Highly recommend. Thank you, BTS, Big Hit, HYBE.",
 "a nice addition to my collection who doesn't love Dolly Parton!!!!",
 "Sounds like Behemoth This is a decent album, but doesn't stand out.  It'll get listened to from time to time.",
 'Five Stars Another great compilation by Coco Montoya!',
 "Love it This CD has various singers on it, not just Ashley.  If you are a fan of Jerry Jeff Walker, you will love this CD.  I'm very happy with the purchase.",
 'Best album yet! I love every song on this album!',
 "Great CD by Ozzy. I gave this as a gift for Christmas, but I also received one the same day.  Love the music.  One of Ozzy's better CDs.  A couple of the songs sound a bit similar to ones he put out about 10 years ago.",
 'super concert 100 0/0 cover and booklet came wet? CD /super concert 100 0/0 cover and booklet came wet?',
 'Awesome record This is a great record at a great price!',
 'Blasphemy! Yeah I held off on getting this awhile. I thought it an unnecessary remix of a perfect, beautifully evil album that I have adored forever, held in a special place in my heart, and I was having none of it. How dare you! Money grabbers!<br /><br />I was wrong wrong wrong. Amazon kept shoving it in my face as a recommendation, as something I might wanna buy. And kept going “blehh” no I don’t, no YOU don’t, Al Gorhythm, and no I won’t!<br /><br />But I finally gave it a glancing preview of a listen, and noticed a few little things like roaring controlled guitar flourishes, keyboards that sounded like the guy from Wish You Were Here was  actually playing on this record, Roger Waters sounding clear and vulnerable, and one of the most underrated drummers of our time finally getting his due.',
 'Get If you get just one re-release with extra live stuff, this is it.<br />It makes Exit irrelevant; Camera Eye and Red Barchetta are pure joy.<br />Geddy likely didn’t believe at the time this was going to be a live record, so he is loose but tight, in a good way, not striving so hard for that famous Rush perfection we are all so familiar with. And they know MP is THE record, this is THE tour, they’re on their way up like a rocket, and they sound like it.<br />The percussion is sooo good, it makes me wanna cry.',
 'Very disappointing. Check out other albums, “Into The Silent Planet” and “Gretchen Goes to Nebraska” These guys are great writers and musicians when it come to rock. They have the harmonies of The Beatles and the punch of Led Zeppelin but this latest album lacks both of those sounds. They’ve recorded over 15 albums which I own but this one is a stinker. Go on YouTube and listen to “We We’re Born To Be Loved”, “Dogman”, “Lost In Germany” and “Goldilocks” for some great rock samples..',
 'I needed a newer copy of this album So glad they still produce vinyl records, my previous version of this album was damaged, so this is a replacement.  Price is too high for me, personally, but I really wanted to listen to this again.',
 'A must buy Elvin Bishop has such a great voice and sings like he telling a story, most of which are funny, I love this cd',
 'Straight from the documentary! Did you love the documentary, but wanted the music too?!  Well, here ya go!  Sounds FANTASTIC!',
 'call me if you get lost album My teen loves this album',
 'Awesome 👏 I love ❤️ It. Can’t wait to see him again.',
 'good stuff listen to it. music to tap your foot to.',
 'This ain\'t Rush, this ain\'t Rush Lite, this ain\'t Victor... this is Envy of None! ... and this IS a great album! Those naysayers whining that this doesn\'t sound like Rush have obviously not been paying attention... Rush as an entity putting out new music doesn\'t exist anymore. This isn\'t Alex and Geddy and some Neil wannabe. This is Alex and Alf and Andy and Maiah.  This album is atmospheric and ethereal and moody. There are touches here and there that clue you into Alex\'s presence, especially the opening to "Spy House". But Alex has made It abundantly clear that this isn\'t a solo recording... this it a band/collaboration project with all 4 members bringing stuff to the table.  Sit alone, in the dark, perhaps while driving, and listen to this music... it\'s captivating.',
 "Blues is a rocking! Started with the Alligator Records 40th Anniversary Collection and now have this 45th and just bought and waiting on the 35th.  I don't know that i have ever had any multi-cd i have bought give me so many great songs throughout the cd's.  If you like a more bluesy but at times rocking mix of music this (and the others) are great to have in your collection.  Love the music, just wish it wasn't every 5 years!!!!",
 "Great compilation I am not a professional product rater such as appears on Amazon so much (are they paid by companies to do this?), just a regular person.  As such I am not going to tell you every little detail about this compilation, one because I don't have the time and 2 because why don't you just listen to it.  But I will say this has been one of the more enjoyable purchases of music i have made in the last few years and if you are a music lover and like this type of music you won't go wrong buying this.",
 "Why? I'm a huge Dolly fan, but I'm left befuddled at why yet another Greatest Hits album is needed.  There are seemingly dozens of them already, and real Dolly fans already have these tracks.  Odd.",
 "Nothing New Here If you're a Madonna fan, you've heard these versions untold times already.  Even if some are slightly different, you're more than familiar with the tunes.  As in the case with most Madonna songs, these have been remixed and rehashed plenty of times before, when they were first released.  Save your money if you don't already have a free streaming service and listen to half of these songs in their original versions.  The other half (the later years' songs) are trash anyway.",
 "Big fan, new and old. Yes it's different than the old stuff, does not mean it's bad. Music is all about how you feel when you listen to it and this is really good.",
 'Great CD Great CD',
 "Larry McCray rocks. We watched Larry McCray perform at Friday Night Live in Saginaw, Michigan and we were amazed at his talent. This guy should be up there with the other Blues legends. I bought the CD for my husband's birthday and he LOVES it.",
 'The best thrash album this year! Holy crap!  This album just annihilates.  These guys just rocketed up from virtually unknown to the top of the thrash heap.  This album verges on the edge of total chaos, but it so tight.  I saw these guys live about 2 months ago and it was one of the best gigs I ever was at.  And I’ve been to over 300.  I don’t know how they pull off these insane riffs at those speeds without sounding sloppy.<br /><br />The only negative thing about this album is that it is only an EP.  We want more!',
 'Excellent Return to Form Skid Row is BACK! I doubt there will be any better hard/classic rock release this year. The highlight, as every other reviewer as proclaimed, is Eric Gronwall\'s vocals. He\'s everything Sebastian ever was and has his own style to boot. These tracks are classic Skid Row but aren\'t dated either so whether you\'re an original fan of the band or new to the party, you\'ll appreciate The Gang\'s All Here. The first couple of tracks are attention-getters, but I recommend "October\'s Song" too-more of an epic. "Time Bomb" is a good track, but who else remembers Saliva\'s 2001 hit "Tick Tick Boom?" Skid Row owes them.<br /><br />I repeat, Highly Recommended.',
 'Megadeth is Back-The Best of Thrash Metal This album has all the elements, attributes of Megadeth that its fans love; it is a complete triumph for Dave M. and co. Whether is Dave Mustaine\'s riffing and songwriting, his speaking (maybe a little too much), guitarist Kiko Loureiro\'s shredding, or even Dirk Verbeuren\'s fantastically creative drumming, Megadeth delivers the best thrash metal record in years. I believe this album is close to my 2 favorites, Rust in Peace and Countdown to Extinction.<br /><br />On the subject of speaking, thanks to Ice T, who performs on "Night Stalkers", great performance and choice. Also, Dave\'s voice is indeed raspy, owing to his 2019 throat cancer but still instantly recognizable.<br /><br />I think the song order is a little curious and off; the better songs are in the second half of the disc, but there\'s no filler at all here.<br /><br />What I love the most about this album is that Dave isn\'t trying to change/morph/update Megadeth into something else; He knows what they do best and  what fans love, and he and this band absolutely deliver.<br /><br />P.S. Salute to the subject of "Night Stalker," the 160th SOAR- "We Own the Night."',
 'Still Love Buble\'s Voice but Not My Favorite I like this album and MB\'s voice more than ever, but to be honest it isn\'t my favorite. Actually on initial listen I wasn\'t enthusiastic, but its growing on me. I\'m trying to getting into Michael\'s songwriting, but "I\'ll Never Not.." the title track, and "Mother" are not Michael Buble classics as far as I\'m concerned. My highlights do include "Crazy" with Willie Nelson, produced by Bob Rock and "My Valentine," produced by originator Paul McCartney. Altogether there\'s lots of musical diversity. It\'s more original than most of his catalog, but the more Sinatra-esque songs will always be my favorites.<br /><br />As Buble claims in the liner notes, this is a hugely ambitious project"- even visionary. Taken in this context, Higher may be Buble\'s best album to date, but it isn\'t my favorite. I prefer It\'s Time and Call Me Irresponsible, so this is just a 4 star for me but may be 5 stars for another fan.',
 'LOVE DOLLY!! Great album, I highly revommend it!!',
 'These guys push the boundaries This is my first time checking this group out based on reviews I have read. I am so impressed by the music they do and the approach to making music. Worth purchasing!',
 'Great disc! I really heard what the songwriter was getting across. The CD sounds great cranked up!',
 'Nothing like his previous cd This cd sounds like a producer tried to commercialize it. Too much unnecessary instrumentation and noise. The intimacy storytelling of his previous cd is missing here. Disappointed',
 "If you are a TP Fan... And you don't have this set, your Music Library is not complete. So many amazing covers mixed in with his music. It's a delight. It's tight. They sound so incredibly good.<br /><br />It breaks my heart a little.",

In [35]:
embeddings_reviews=get_embedding_batch(text_to_embed_reviews,batch_size=500)

Processed batch 1 of 18
Processed batch 2 of 18
Processed batch 3 of 18
Processed batch 4 of 18
Processed batch 5 of 18
Processed batch 6 of 18
Processed batch 7 of 18
Processed batch 8 of 18
Processed batch 9 of 18
Processed batch 10 of 18
Processed batch 11 of 18
Processed batch 12 of 18
Processed batch 13 of 18
Processed batch 14 of 18
Processed batch 15 of 18
Processed batch 16 of 18
Processed batch 17 of 18
Processed batch 18 of 18

In [36]:
len(embeddings_reviews)

8721

In [37]:
pointstructs=[]
i=1
for embedding, data in zip(embeddings_reviews, data_to_embed_reviews):
    pointstructs.append(
        PointStruct(
            id=i,
            vector=embedding,
            payload={
                "text": data["preprocessed_data"],
                "parent_asin": data["parent_asin"]
            }
        )
    )
    i += 1

In [38]:
batch_size_qdrant=100
counter=1
for i in range(0, len(pointstructs), batch_size_qdrant):
    batch=pointstructs[i:i+batch_size_qdrant]
    qdrant_client.upsert(
        collection_name="amazon-items-collection-02-openai-small-reviews",
        wait=True,
        points=batch
    )
    print(f"Processed batch {counter} of {len(pointstructs)//batch_size_qdrant + 1}")
    counter += 1

Processed batch 1 of 88
Processed batch 2 of 88
Processed batch 3 of 88
Processed batch 4 of 88
Processed batch 5 of 88
Processed batch 6 of 88
Processed batch 7 of 88
Processed batch 8 of 88
Processed batch 9 of 88
Processed batch 10 of 88
Processed batch 11 of 88
Processed batch 12 of 88
Processed batch 13 of 88
Processed batch 14 of 88
Processed batch 15 of 88
Processed batch 16 of 88
Processed batch 17 of 88
Processed batch 18 of 88
Processed batch 19 of 88
Processed batch 20 of 88
Processed batch 21 of 88
Processed batch 22 of 88
Processed batch 23 of 88
Processed batch 24 of 88
Processed batch 25 of 88
Processed batch 26 of 88
Processed batch 27 of 88
Processed batch 28 of 88
Processed batch 29 of 88
Processed batch 30 of 88
Processed batch 31 of 88
Processed batch 32 of 88
Processed batch 33 of 88
Processed batch 34 of 88
Processed batch 35 of 88
Processed batch 36 of 88
Processed batch 37 of 88
Processed batch 38 of 88
Processed batch 39 of 88
Processed batch 40 of 88
Processed batch 41 of 88
Processed batch 42 of 88
Processed batch 43 of 88
Processed batch 44 of 88
Processed batch 45 of 88
Processed batch 46 of 88
Processed batch 47 of 88
Processed batch 48 of 88
Processed batch 49 of 88
Processed batch 50 of 88
Processed batch 51 of 88
Processed batch 52 of 88
Processed batch 53 of 88
Processed batch 54 of 88
Processed batch 55 of 88
Processed batch 56 of 88
Processed batch 57 of 88
Processed batch 58 of 88
Processed batch 59 of 88
Processed batch 60 of 88
Processed batch 61 of 88
Processed batch 62 of 88
Processed batch 63 of 88
Processed batch 64 of 88
Processed batch 65 of 88
Processed batch 66 of 88
Processed batch 67 of 88
Processed batch 68 of 88
Processed batch 69 of 88
Processed batch 70 of 88
Processed batch 71 of 88
Processed batch 72 of 88
Processed batch 73 of 88
Processed batch 74 of 88
Processed batch 75 of 88
Processed batch 76 of 88
Processed batch 77 of 88
Processed batch 78 of 88
Processed batch 79 of 88
Processed batch 80 of 88
Processed batch 81 of 88
Processed batch 82 of 88
Processed batch 83 of 88
Processed batch 84 of 88
Processed batch 85 of 88
Processed batch 86 of 88
Processed batch 87 of 88
Processed batch 88 of 88

#### function to run search against reviews on a prefiltered set of product IDs

In [39]:
def retrieve_prefiltered_reviews_data(query, parent_asins,k=5):
    query_embedding=get_embedding(query)
    results=qdrant_client.query_points(
        collection_name="amazon-items-collection-02-openai-small-reviews",
        prefetch=[
            Prefetch(
                query=query_embedding,
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin",
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )
    return results

#### the test say a review with bad quality in a set of parent-asins

In [42]:
reviews=retrieve_prefiltered_reviews_data("bad quality", ["B09F1FJCH6"],k=5)

In [44]:
reviews.points

[ScoredPoint(id=2680, version=31, score=0.5, payload={'text': 'So so quality Quality is not what I want', 'parent_asin': 'B09F1FJCH6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=4672, version=51, score=0.33333334, payload={'text': 'Pressing Not Very Good This is a great album but the pressing isn’t so great. A lot of particles in the vinyl. If you’re picky about vinyl quality you will probably be disappointed.', 'parent_asin': 'B09F1FJCH6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=4103, version=46, score=0.25, payload={'text': 'Inexpensive but not 180g Sounds good, but not an audiophile quality pressing by any means.', 'parent_asin': 'B09F1FJCH6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=8277, version=87, score=0.2, payload={'text': 'Sony Music, get your QC together Highway 61 Revisited sleeve, Highway 61 Revisited label, but the actual record was Bringing It All Back Home. Nonexistent QC. Sony more concerned with pressing another 100K Adele albums?<br /><br />Follow-up: Replacement record received. This time, it was the correct record.', 'parent_asin': 'B09F1FJCH6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=2855, version=33, score=0.16666667, payload={'text': 'Warped disc I love Bob Dylan , but do not like warped records; it went back', 'parent_asin': 'B09F1FJCH6'}, vector=None, shard_key=None, order_value=None)]

In [45]:
for point in reviews.points:
    print(point.payload["parent_asin"])
    print(point.payload["text"])
    print("="*100)

B09F1FJCH6
So so quality Quality is not what I want
====================================================================================================
B09F1FJCH6
Pressing Not Very Good This is a great album but the pressing isn’t so great. A lot of particles in the vinyl. If you’re picky about vinyl quality you will probably be disappointed.
====================================================================================================
B09F1FJCH6
Inexpensive but not 180g Sounds good, but not an audiophile quality pressing by any means.
====================================================================================================
B09F1FJCH6
Sony Music, get your QC together Highway 61 Revisited sleeve, Highway 61 Revisited label, but the actual record was Bringing It All Back Home. Nonexistent QC. Sony more concerned with pressing another 100K Adele albums?<br /><br />Follow-up: Replacement record received. This time, it was the correct record.
====================================================================================================
B09F1FJCH6
Warped disc I love Bob Dylan , but do not like warped records; it went back
====================================================================================================